### ISSUE TITLE
Update Library for Release-Ready

### ISSUE THREAD

**Issue by BatiGencho** [massalabs/massa-web3#130]
# Objective
The purpose of this issue is to ensure that the library is updated to meet the expected criteria for an application to be maintained and considered release-ready. The requirements are outlined in the Run team procedure: [Definition of Release-Ready](https://www.notion.so/massa-innoteam/Definition-of-Release-Ready-964a4f2ffd9549129edf76d6c623c490).

# Tasks
This issue is a meta issue. Please create additional issues to perform the task and reference them. Keep in mind that the issues should be as short as possible to improve overall efficiency.

## Testing

- [x] Include test coverage
- [x] #217

### Improve test coverage 

- [x] #223

## Documentation 

- [x] #139

### Code documentation

- [x] #146
- [x] #164
- [x] #152

### Git Documentation

- [x] #151
- [x] #213
- [x] Add license
- [x] #249

## Security

- [ ]  Define a security model
- [x]  Implement proper countermeasures, such as static analysis of code and security checks of dependencies

## Automation
- [x] #208
- [x]  Automate tasks that can be automated
- [x] #137
- [x] #228

## Compatibility
- [x] #221
- [x] #211

## Must have
- [x] #230

## Wrap Up

- [ ]  Ensure that the Run team procedure was properly applied and update the document if necessary
- [ ]  Communicate that the library is now considered release-ready
