### ISSUE TITLE
Improve Massa-web3 test

### ISSUE THREAD

**Issue by julienbrs** [massalabs/massa-web3#258]
# Objective
For the moment, we only have tests for some files of src/utils. We should improve coverage by testing core logic of massa-web3, by unit testing src/web3

# Tasks
Create a unit tests file for each file of src/web3
- [x] #261
- [x] #284
- [x] test Client.ts
- [x] test ClientFactory.ts
- [x] test EventPoller.ts
- [x] #315
- [x] test SmartContractsClient.ts
- [x] #269
